
package cat.apuntstecnologia.proves.jeeclientws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServeiProvaService", targetNamespace = "http://proves.apuntstecnologia.cat/", wsdlLocation = "http://localhost:8080/jeews/ServeiProva?wsdl")
public class ServeiProvaService
    extends Service
{

    private final static URL SERVEIPROVASERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVEIPROVASERVICE_EXCEPTION;
    private final static QName SERVEIPROVASERVICE_QNAME = new QName("http://proves.apuntstecnologia.cat/", "ServeiProvaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jeews/ServeiProva?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVEIPROVASERVICE_WSDL_LOCATION = url;
        SERVEIPROVASERVICE_EXCEPTION = e;
    }

    public ServeiProvaService() {
        super(__getWsdlLocation(), SERVEIPROVASERVICE_QNAME);
    }

    public ServeiProvaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVEIPROVASERVICE_QNAME, features);
    }

    public ServeiProvaService(URL wsdlLocation) {
        super(wsdlLocation, SERVEIPROVASERVICE_QNAME);
    }

    public ServeiProvaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVEIPROVASERVICE_QNAME, features);
    }

    public ServeiProvaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServeiProvaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServeiProva
     */
    @WebEndpoint(name = "ServeiProvaPort")
    public ServeiProva getServeiProvaPort() {
        return super.getPort(new QName("http://proves.apuntstecnologia.cat/", "ServeiProvaPort"), ServeiProva.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServeiProva
     */
    @WebEndpoint(name = "ServeiProvaPort")
    public ServeiProva getServeiProvaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://proves.apuntstecnologia.cat/", "ServeiProvaPort"), ServeiProva.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVEIPROVASERVICE_EXCEPTION!= null) {
            throw SERVEIPROVASERVICE_EXCEPTION;
        }
        return SERVEIPROVASERVICE_WSDL_LOCATION;
    }

}
