
package cat.apuntstecnologia.proves.jeeclientws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServeiProva", targetNamespace = "http://proves.apuntstecnologia.cat/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServeiProva {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "concatena", targetNamespace = "http://proves.apuntstecnologia.cat/", className = "cat.apuntstecnologia.proves.jeeclientws.Concatena")
    @ResponseWrapper(localName = "concatenaResponse", targetNamespace = "http://proves.apuntstecnologia.cat/", className = "cat.apuntstecnologia.proves.jeeclientws.ConcatenaResponse")
    public String concatena(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suma", targetNamespace = "http://proves.apuntstecnologia.cat/", className = "cat.apuntstecnologia.proves.jeeclientws.Suma")
    @ResponseWrapper(localName = "sumaResponse", targetNamespace = "http://proves.apuntstecnologia.cat/", className = "cat.apuntstecnologia.proves.jeeclientws.SumaResponse")
    public int suma(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "quinDiaEsAvui", targetNamespace = "http://proves.apuntstecnologia.cat/", className = "cat.apuntstecnologia.proves.jeeclientws.QuinDiaEsAvui")
    @ResponseWrapper(localName = "quinDiaEsAvuiResponse", targetNamespace = "http://proves.apuntstecnologia.cat/", className = "cat.apuntstecnologia.proves.jeeclientws.QuinDiaEsAvuiResponse")
    public String quinDiaEsAvui();

}
